# Generated by Django 3.2.7 on 2021-09-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_articlo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=10)),
                ('Doctor', models.BooleanField()),
                ('gender_choice', models.CharField(choices=[('1', 'male'), ('2', 'female'), ('3', 'non binary'), ('4', 'Trans')], default='1', max_length=20)),
            ],
        ),
    ]
