# Generated by Django 3.2.7 on 2021-11-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_newmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.TextField()),
                ('mobile', models.TextField()),
                ('pwd', models.TextField()),
            ],
        ),
    ]
