# Generated by Django 3.2.7 on 2021-11-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_adoptpet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=40)),
            ],
        ),
    ]
