# Generated by Django 3.2.7 on 2021-11-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='experience',
            field=models.TextField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.TextField(default='none', max_length=50),
        ),
    ]
