# Generated by Django 3.2.7 on 2021-11-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211118_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptpet',
            name='pic',
        ),
    ]
